layout_spectrum: 0.2956989
typography_spectrum: 0.4928315
color:
  saturation: 0.2885305
  brandStrength: 0.7185139
  lightness: 0.3207885
  brandColors:
    - '#F4F4E8'
    - '#D9BCA4'
    - '#0D0304'
    - '#928990'
    - '#E7031D'
  rhythmicContrast: 0.2204301
name: Geekest-Link.com
